name: task_manager
description: "A new Flutter task manager project."

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  widget_and_text_animator: ^1.1.5
  gap: ^3.0.1
  provider: ^6.1.2
  http: ^1.2.1
  awesome_snackbar_content: ^0.1.3
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  ionicons: ^0.2.2
  salomon_bottom_bar: ^3.3.2
  image_picker: ^1.1.2
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Regular.ttf
     - family: Poppins Bold
       fonts:
         - asset: assets/fonts/Poppins-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
