import 'package:flutter/material.dart';

class AppColor {
  static const Color appPrimaryColor = Color(0xFF21BF73);
  static const Color darkComponentsColor = Color(0xFF222222);
  static const Color scaffoldBackgroundColorLight = Color(0xFFFAF8F6);
  static const Color scaffoldBackgroundColorDark = Color(0xFF282828);
  static const Color headLineTextLargeColorLight = Colors.black;
  static const Color headLineTextLargeColorDark = Colors.white;
  static const Color bodySmallTextColor = Colors.grey;
  static const Color bodyMediumTextColorLight = Colors.black;
  static const Color bodyMediumTextColorDark = Colors.white;
  static const Color labelSmallTextColor = Colors.white;
  static Color textFieldHintColor = Colors.grey.shade400;
  static const Color elevatedButtonForegroundColor = Colors.white;
  static const Color circularProgressbarColor = Colors.white;
  static const Color snackBarSuccessColor = appPrimaryColor;
  static Color snackBarFailureColor = Colors.red.shade300;
  static Color snackBarWarningColor = const Color(0xFFFFCC00);
  static const Color appBarForegroundColor = Colors.white;
  static const Color appBarBackgroundColorLight = appPrimaryColor;
  static const Color appBarBackgroundColorDark = darkComponentsColor;
  static const Color bottomBarUnselectedColor = Colors.black;
  static const Color bottomBarSelectedColor = appPrimaryColor;
  static const Color bottomBarBackgroundColor = scaffoldBackgroundColorLight;
  static Color newTaskChipColor = const Color(0xFF17C1E8);
  static const Color completedChipColor = appPrimaryColor;
  static Color progressChipColor = const Color(0xFFCB0C9F);
  static Color canceledChipColor = const Color(0xFFF15056);
  static const Color newTaskChipTextColor = Colors.white;
  static const Color deleteIconColor = Colors.red;
  static const Color editIconColor = appPrimaryColor;
  static const Color photoPickerColor = Colors.grey;
  static const Color cardBackgroundColorLight = Colors.white;
  static const Color cardBackgroundColorDark = darkComponentsColor;
  static const Color textFieldColorDark = darkComponentsColor;
  static const Color popupMenuColorLight = Colors.white;
  static const Color popupMenuColorDark = darkComponentsColor;
  static const Color expansionTileCollapsedIconColor = Colors.grey;
}
